#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_shotgun.humann2 import plugin as h2_plugin
from qp_shotgun.kneaddata import plugin as kd_plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='source activate qp-shotgun')
@click.option('--server-cert', prompt='Server certificate', default='None')
def config(env_script, server_cert):
    """Generates the Qiita configuration files"""
    if server_cert == 'None':
        server_cert = None
    kd_plugin.generate_config(env_script, 'start_shotgun',
                           server_cert=server_cert)
    h2_plugin.generate_config(env_script, 'start_shotgun',
                           server_cert=server_cert)

if __name__ == '__main__':
    config()
